#!/bin/sh

# Job Name
#$ -N VRC607_selection

# Execute the script from the current working directory
#$ -cwd

# Merge the output of the script (and any error messages generated) into one file
#$ -j y

# Send the output of the script to a directory called 'UGE-output' in the current working directory (cwd)
#$ -o UGE-output/

# Send mail when the job is submitted, and when the job completes
#$ -m be

#  Specify an email address to use
#$ -M millerkrs@nih.gov


# load Python
module load python

echo 'Simplifying FUBAR data'
# Run the program to simplify FUBAR data
python3 scripts/simplify_fubar_data.py -d data/VRC607

echo 'Translating alignments'
# Run the program to translate all the alignment files
python3 scripts/translate_fasta.py -d data/VRC607

echo 'Getting consensus sequences'
# Run the program to get consensus sequences from translated alignment files
python3 scripts/create_aa_consensus.py -o VRC607_consensus_seqs.fa -d data/VRC607

# Append HXB2 protein sequence to file with consensus sequences
cat data/VRC607/VRC607_consensus_seqs.fa data/hxb2_aa.fa >> data/VRC607/VRC607_consensus_seqs_hxb2.fa

# Unload Python
module unload python


# Load alignment software MAFFT
module load mafft

echo 'Aligning consensus protein sequences to HXB2'
# Align translated consensus sequences with HXB2
mafft data/VRC607/VRC607_consensus_seqs_hxb2.fa > results/VRC607/VRC607_hxb2_aln.fa

# Unload MAFFT
module unload mafft


# Load Python
module load python

echo 'Getting codon position mappings from the alignment'
# Get codon position mappings of HXB2 -> Aligned Consensus -> Original Consensus
python3 scripts/get_position_mappings.py -c data/VRC607/VRC607_consensus_seqs.fa -a results/VRC607/VRC607_hxb2_aln.fa -d results/VRC607/

# Unload Python
module unload python


# Load R
module load R

# Use output files to get annotations for consensus sequences
Rscript scripts/get_annotation_for_consensus.R --args data/ results/VRC607/

# Unload R
module unload R


echo "All done!"


